### ISSUE TITLE
Оставить только необходимые зависимости для подключения .h файла

### ISSUE THREAD

**Issue by naljaka** [rusteRR/Jackal#3]
https://github.com/rusteRR/Jackal/blob/f64b8d84c5acbe548e0ae13a002fcf0fe0586d9d/include/field.h#L4

в самом хедере должен быть только необходимый и достаточный перечень зависимостей, требуемых для работы с интерфейсом класса, описанном в этом файле. Если под капотом этот файл что-то использует еще, то подключить это следует в .cpp. 
Это делается для того, чтобы при инклуде требуемого класса не тащить за ним вагон зависимостей, хотя снаружи они не будут использованы

**Comment by rusteRR** [comment]
Fixed
